name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0,30 * * * *" }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: Asia/Shanghai
#           config_display: columns

          plugin_achievements: yes
          plugin_achievements_threshold: B

          plugin_activity: yes

          plugin_gists: yes

          plugin_habits: yes
          plugin_habits_charts: yes

          plugin_isocalendar: yes

          plugin_notable: yes
          plugin_notable_repositories: yes

          plugin_traffic: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 0
          
          plugin_lines: yes
