name: Profile Cards
on:
  schedule: [{ cron: "7 * * * *" }]
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  profile-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: vn7n24fzkq/github-profile-summary-cards@e722eded97059b31d7e8ad3ae0267b74ff24172d # main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          UTC_OFFSET: 8
          THEME: github
          AUTO_PUSH: false

      - uses: vn7n24fzkq/github-profile-summary-cards@e722eded97059b31d7e8ad3ae0267b74ff24172d # main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          UTC_OFFSET: 8
          THEME: github_dark
          AUTO_PUSH: false

      - uses: stats-organization/github-readme-stats-action@2c498845f71017821efaad14293ebc736156ef21 # v2
        with:
          card: stats
          options: show_icons=true&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - uses: stats-organization/github-readme-stats-action@2c498845f71017821efaad14293ebc736156ef21 # v2
        with:
          card: stats
          options: show_icons=true&hide_border=true&theme=github_dark
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A profile/ profile-summary-card-output/
          git commit -m "Update profile cards" || exit 0
          git push
